// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:176f43fe-b2ca-4eb2-90e6-0df4a9ec4360",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_q0H74lUL2",
    "aws_user_pools_web_client_id": "1eafgnebde62gpc4vnal8m950s",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "main",
            "region": "us-west-2"
        }
    ],
    "aws_user_files_s3_bucket": "pm3storage1bucket1",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_mobile_analytics_app_id": "296c28c902ef41f8abefaf990ab3ab09",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
